name: 'Setup Tech Stack'
description: 'Sets up the required tech stack based on app configuration'

inputs:
  app-dir:
    description: 'Directory of the application'
    required: true
  config-path:
    description: 'Path to the config.json file'
    required: true
    default: './config.json'

runs:
  using: 'composite'
  steps:
    - name: Read config
      id: config
      shell: bash
      run: |
        CONFIG=$(jq -c --arg app "${{ inputs.app-dir }}" '.apps[$app]' ${{ inputs.config-path }})
        echo "config=$CONFIG" >> $GITHUB_OUTPUT
        echo "type=$(echo "$CONFIG" | jq -r '.type')" >> $GITHUB_OUTPUT
        echo "version=$(echo "$CONFIG" | jq -r '.version')" >> $GITHUB_OUTPUT
        echo "install_command=$(echo "$CONFIG" | jq -r '.["install-command"]')" >> $GITHUB_OUTPUT
        echo "test_command=$(echo "$CONFIG" | jq -r '.["test-command"]')" >> $GITHUB_OUTPUT
        echo "build_command=$(echo "$CONFIG" | jq -r '.["build-command"]')" >> $GITHUB_OUTPUT

    # ───────────────────────────────────────────
    # NODE
    # ───────────────────────────────────────────
    - name: Setup Node.js
      if: ${{ steps.config.outputs.type == 'node' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.config.outputs.version }}

    # ───────────────────────────────────────────
    # PYTHON
    # ───────────────────────────────────────────
    - name: Setup Python
      if: ${{ steps.config.outputs.type == 'python' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ steps.config.outputs.version }}

    # ───────────────────────────────────────────
    # FLUTTER
    # ───────────────────────────────────────────
    - name: Setup Flutter
      if: ${{ steps.config.outputs.type == 'flutter' }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.config.outputs.version }}

    # ───────────────────────────────────────────
    # JAVA
    # ───────────────────────────────────────────
    - name: Setup Java
      if: ${{ steps.config.outputs.type == 'java' }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ steps.config.outputs.version }}
        distribution: 'temurin'

    # ───────────────────────────────────────────
    # GO
    # ───────────────────────────────────────────
    - name: Setup Go
      if: ${{ steps.config.outputs.type == 'go' }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.config.outputs.version }}

    # ───────────────────────────────────────────
    # Shared build steps
    # ───────────────────────────────────────────
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: ${{ steps.config.outputs.install_command }}

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: ${{ steps.config.outputs.test_command }}
      continue-on-error: false

    - name: Build application
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: ${{ steps.config.outputs.build_command }}
